# docker-compose.yml
version: "3.9"

services:
  frontend:
    build: ./frontend/
    ports:
      - "5173:5173"
  app:
    build: ./api/
    ports:
      - "3000:3000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
