# docker-compose.yml
version: "3.9"

services:
  app:
    image: "oven/bun"
    # override default entrypoint allows us to sdo `bun install` before serving
    entrypoint: []
    # execute bun install before we start the dev server in watch mode
    command: "/bin/sh -c 'bunx prisma generate &&
    bun install && bun run --watch src/index.ts'"
    # expose the right ports
    ports: ["3000:3000"]
    networks:
      - dev-network
    # setup a host mounted volume to sync changes to the container
    volumes: ["./:/home/bun/app"]
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - dev-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks: 
  dev-network:
      driver: bridge